---
server:
  host: localhost
  port: 8080
  timeout:
    server: 30
    read: 15
    write: 10
    idle: 5
  cors:
    allowCredentials: true
    allowedHeaders:
      - X-CSRF-Token  # must be the same as configured CSRF Header
    exposedHeaders:
      - X-CSRF-Token  # must be the same as configured CSRF Header
    allowedOrigins:
      - http://localhost*  # wildcard allows for varying port values in origin during development
    debug: true
  csrf:
    secure: false  # false in development only!
    key: place-your-32-byte-long-key-here
    cookieName: csrf
    header: X-CSRF-Token
